# This is a basic workflow to help you get started with Actions

name: Deploy to Github Pages

# Controls when the action will run. 
on:
  # Triggers the workflow on push to main
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          # Optional version of wasm-pack to install(eg. 'v0.9.1', 'latest')
          version: 'v0.9.1'

      # Runs a set of commands using the runners shell
      - name: Compile to WASM
        run: |
          cd $GITHUB_WORKSPACE/tactician-bevy
          wasm-pack build --target web --release -- --features wasm
          
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: tactician-bevy/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
